export enum State {
    INIT = 'INIT',
    STARTING = 'STARTING',
    STOPPING = 'STOPPING',
    RUNNING = 'RUNNING',
    STOPPED = 'STOPPED',
    ERRORED = 'ERRORED',
    STARTING_SERVICES = 'STARTING_SERVICES',
    STOPPING_SERVICES = 'STOPPING_SERVICES',
}